CREATE TABLE tankemBalance(
	charsVitese NUMBER NOT NULL,
	charsVitesseRotation NUMBER NOT NULL,
	charsPointsDeVie NUMBER NOT NULL,
	blocsTempsMouvement NUMBER NOT NULL,
	canonVitesseBalle NUMBER NOT NULL,
	canonTempsRecharge NUMBER NOT NULL,
	mitrailletteVitesseBalle NUMBER NOT NULL,
	mitrailletteTempsRecharge NUMBER NOT NULL,
	grenadeVitesseInitialeBalle NUMBER NOT NULL,
	grenadeTempsRecharge NUMBER NOT NULL,
	shotgunVitesseBalle NUMBER NOT NULL,
	shotgunTempsRecharge NUMBER NOT NULL,
	shotgunOuvertureFusil NUMBER NOT NULL,
	piegeVitesseBalle NUMBER NOT NULL,
	piegeTempsRecharge NUMBER NOT NULL,
	missileGuideVitesseBalle NUMBER NOT NULL,
	missileGuideTempsRecharge NUMBER NOT NULL,
	springVitesseInitialeSaut NUMBER NOT NULL,
	springTempsRecharge NUMBER NOT NULL,
	explosionBallesGrosseur NUMBER NOT NULL,
	messageAccueilDuree NUMBER NOT NULL,
	messageCompteRebour NUMBER NOT NULL,
	messageAccueilContenu VARCHAR2(60),
	messageSignalDebutpartie VARCHAR2(50),
	messageFinPartie VARCHAR2(70),
	CONSTRAINT CK_charsVitese CHECK (charsVitese BETWEEN 4.0 AND 12.0),
	CONSTRAINT CK_charsVitesseRotation CHECK (charsVitesseRotation BETWEEN 1000.0 AND 2000.0),
	CONSTRAINT CK_charsPointsDeVie CHECK (charsPointsDeVie BETWEEN 100.0 AND 2000.0),
	CONSTRAINT CK_blocsTempsMouvement CHECK (blocsTempsMouvement BETWEEN 0.2 AND 2.0),
	CONSTRAINT CK_canonVitesseBalle CHECK (canonVitesseBalle BETWEEN 4.0 AND 30.0),
	CONSTRAINT CK_canonTempsRecharge CHECK (canonTempsRecharge BETWEEN 0.2 AND 10.0),
	CONSTRAINT CK_mitrailletteVitesseBalle CHECK (mitrailletteVitesseBalle BETWEEN 4.0 AND 30.0),
	CONSTRAINT CK_mitrailletteTempsRecharge CHECK (mitrailletteTempsRecharge BETWEEN 0.2 AND 10.0),
	CONSTRAINT CK_grenadeVitesseInitialeBalle CHECK (grenadeVitesseInitialeBalle BETWEEN 10 AND 25.0),
	CONSTRAINT CK_grenadeTempsRecharge CHECK (grenadeTempsRecharge BETWEEN 0.2 AND 10.0),
	CONSTRAINT CK_shotgunVitesseBalle CHECK (shotgunVitesseBalle BETWEEN 4.0 AND 30.0),
	CONSTRAINT CK_shotgunTempsRecharge CHECK (shotgunTempsRecharge BETWEEN 0.2 AND 10.0),
	CONSTRAINT CK_shotgunOuvertureFusil CHECK (shotgunOuvertureFusil BETWEEN 0.1 AND 1.5),
	CONSTRAINT CK_piegeVitesseBalle CHECK (piegeVitesseBalle BETWEEN 0.2 AND 4.0),
	CONSTRAINT CK_piegeTempsRecharge CHECK (piegeTempsRecharge BETWEEN 0.2 AND 10.0),
	CONSTRAINT CK_missileGuideVitesseBalle CHECK (missileGuideVitesseBalle BETWEEN 20.0 AND 40.0),
	CONSTRAINT CK_missileGuideTempsRecharge CHECK (missileGuideTempsRecharge BETWEEN 0.2 AND 10.0),
	CONSTRAINT CK_springVitesseInitialeSaut CHECK (springVitesseInitialeSaut BETWEEN 6.0 AND 20.0),
	CONSTRAINT CK_springTempsRecharge CHECK (springTempsRecharge BETWEEN 0.2 AND 10.0),
	CONSTRAINT CK_explosionBallesGrosseur CHECK (explosionBallesGrosseur BETWEEN 1.0 AND 30.0),
	CONSTRAINT CK_messageAccueilDuree CHECK (messageAccueilDuree BETWEEN 1.0 AND 10.0),
	CONSTRAINT CK_messageCompteRebour CHECK (messageCompteRebour BETWEEN 0.0 AND 10.0),
	CONSTRAINT CK_messageAccueilContenu check (length(messageAccueilContenu) <60),
	CONSTRAINT CK_messageSignalDebutpartie check (length(messageSignalDebutpartie) < 50),
	CONSTRAINT CK_messageFinPartie check (length(messageFinPartie) < 70)
);
INSERT INTO tankemBalance VALUES(7,1500,200,0.8,14,1.2,18,0.4,16,0.8,13,1.8,0.4,1,0.8,30,3,10,0.5,8,3,3,'Bienvenue à TANKEM!','Début de partie!!','Fin de partie!');

Commit;

